spring.application.name=eventanalytics
spring.datasource.url=jdbc:postgresql://localhost:5432/event_analytics
spring.datasource.username=postgres
spring.datasource.password=bits@123
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
