CREATE TABLE IF NOT EXISTS users (
  user_id UUID PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS event_ids (
  event_id UUID PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS events (
  event_id UUID PRIMARY KEY,
  user_id UUID NOT NULL,
  event_type VARCHAR(255) NOT NULL,
  event_time TIMESTAMP NOT NULL,
  properties CLOB,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
